# Generated by Django 6.0.7 on 2026-09-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'ANDAMENTO'), ('F', 'FEITO')], default='P', max_length=1)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
